spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alpha-server
    template:
      default-topic: chat-test
  config:
    activate:
      on-profile: alpha
    redis:
      host: 127.0.0.1
      port: 6379